### ISSUE TITLE
Add support for TSTupleType and TSAbstractClassDeclaration in ast-node-types.js

### ISSUE THREAD

**Issue by vivekgalatage** [JamesHenry/typescript-estree#16]
**What version of TypeScript are you using?**
Typescript 3.0.1

**What code were you trying to parse?**

```ts
class Class {
  method(parameters: [number, string?, boolean?]) {
  }
}

```
Please take a look at the AST explorer snippet for the same 
https://astexplorer.net/#/gist/e5dd1011355354fea561d02cb10e0b05/9ccb97f94ca1871a0f8917bed5b4d95402a07e13

**What did you expect to happen?**
The TSTupleType keyword should be in the ast-node-types.js file.

**What actually happened?**
Support for TSTupleType as ast-node-type is missing.

**Comment by vivekgalatage** [comment]
This also applies to `TSAbstractClassDeclaration`

```ts
abstract class Hello {
  static world(): string {
    return ""
  }
}
```

Please take a look at the AST here 
https://astexplorer.net/#/gist/3b79e871a564de599f26479d58bb5cd8/33d9327299b131a23e78e5e738bef37e2bec5584

So can `TSAbstractClassDeclaration` be added to the ast-node-types.js as well?

**Comment by JamesHenry** [comment]
Thanks for reporting @vivekgalatage, I'm curious in what situation this surfaced as an issue for you?
