### ISSUE TITLE
Evaluate `ecmaFeatures` option

### ISSUE THREAD

**Issue by kaicataldo** [JamesHenry/typescript-estree#21]
**What version of TypeScript are you using?**
N/A

**What version of `typescript-estree` are you using?**
master

**What code were you trying to parse?**
N/A

**What did you expect to happen?**
N/A

**What actually happened?**
N/A

Had a thought while I was looking at https://github.com/eslint/typescript-eslint-parser/pull/530. Now that the ESLint-compatibility layer has been separated out, does it make sense to keep the `ecmaFeatures` option? It looks as though it's only used to enable JSX.

I'm not entirely sure `ecmaFeatures` makes sense for this package - perhaps we could just add either a `jsx: true` or `enableJSX: true` option?

We could always make this backwards compatible, if that's a worry. I'm more than happy to make a PR!

**Comment by JamesHenry** [comment]
Thanks again for doing this
