### ISSUE TITLE
cannot distinguish `declare global` on AST.

### ISSUE THREAD

**Issue by mysticatea** [JamesHenry/typescript-estree#27]
**What version of TypeScript are you using?**

- 3.1.6

**What version of `typescript-estree` are you using?**

- 2.1.0 (typescript-eslint-parser#master)

**What code were you trying to parse?**

```ts
// Augmentations for the global stuff.
declare global {
}

// A namespace declaration.
declare namespace global {
}
```

**What did you expect to happen?**

`typescript-estree` generates different nodes because the two have different semantics.

**What actually happened?**

`typescript-estree` generates the same node:

```json
    {
      "type": "TSModuleDeclaration",
      "id": {
        "type": "Identifier",
        "name": "global"
      },
      "body": {
        "type": "TSModuleBlock",
        "body": []
      },
      "declare": true
    }
```

**Comment by mysticatea** [comment]
`TSGlobalAugmentationDeclaration` node may be nice.

```js
// The node that expresses `declare global {}`.
interface TSGlobalAugmentationDeclaration extends Statement {
    type: "TSGlobalAugmentationDeclaration"
    body: TSModuleBlock
}
```

**Comment by armano2** [comment]
According to babel/typescript its: https://github.com/babel/babel/blob/08454ece462ed870f3c18e1274091e2cfb761085/packages/babel-types/src/definitions/typescript.js#L390

```js
defineType("TSModuleDeclaration", {
  aliases: ["Statement", "Declaration"],
  visitor: ["id", "body"],
  fields: {
    declare: validateOptional(bool),
    global: validateOptional(bool),
    id: validateType(["Identifier", "StringLiteral"]),
    body: validateType(["TSModuleBlock", "TSModuleDeclaration"]),
  },
});
```
