### ISSUE TITLE
Babel vs TSE: TrueKeyword and FalseKeyword

### ISSUE THREAD

**Issue by armano2** [JamesHenry/typescript-estree#58]
Currently we are parsing `TrueKeyword` and `FalseKeyword` as `type='Literal'` when in type, but babel parses them as `BooleanLiteral`,

i'm unsure what we should do with this...

**Comment by armano2** [comment]
Babel expect when used as value:
```ts
const test = true;
```
```json
{
  "type": "Program",
  "sourceType": "script",
  "body": [
	{
	  "type": "VariableDeclaration",
	  "declarations": [
		{
		  "type": "VariableDeclarator",
		  "id": {
			"type": "Identifier",
			"name": "test"
		  },
		  "init": {
			"type": "Literal",
			"value": true,
			"raw": "true"
		  }
		}
	  ],
	  "kind": "const"
	}
  ]
}
```

when used as type:
```ts
type Foo = false
```
```json
{
  "type": "Program",
  "sourceType": "script",
  "body": [
	{
	  "type": "TSTypeAliasDeclaration",
	  "id": {
		"type": "Identifier",
		"name": "Foo"
	  },
	  "typeAnnotation": {
		"type": "TSLiteralType",
		"literal": {
		  "type": "BooleanLiteral",
		  "value": false
		}
	  }
	}
  ]
}
```

**Comment by JamesHenry** [comment]
Hmm yeah, awkward one. IIRC BooleanLiteral is what babel does as standard and then the ESTree plugin converts it to Literal

**Comment by armano2** [comment]
than there is issue in ESTreePlugin than... i will investigate this

**Comment by armano2** [comment]
ok i will investigate that, and most likely report error there

**Comment by armano2** [comment]
https://github.com/babel/babel/issues/9228

**Comment by JamesHenry** [comment]
We're not explicitly tracking any of the other babel issues on this repo so I'm going to close this for consistency with that
